import {
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image7,
  image8,
  image9,
} from "../assets/images";
export default [
  {
    key: 1,
    name: "Earbuds K97Y",
    image: image1,
    price: 99.99,
    description: "Organic's Coton, Confortable",
  },
  {
    key: 2,
    name: "Earbuds Air",
    image: image2,
    price: 39.00,
    description: "The best for sports",
  },
  {
    key: 3,
    name: "Wireless earphones",
    image: image3,
    price: 57.19,
    description: "Premium experince",
  },
  {
    key: 4,
    name: "Ibeats Headsets",
    image: image4,
    price: 79.99,
    description: "Feel in other world",
  },
  {
    key: 5,
    name: "Beats Pro",
    image: image5,
    price: 159.99,
    description: "The best for movies",
  },
  {
    key: 6,
    name: "Silver Monster",
    image: image6,
    price: 200.99,
    description: "Get a premium experience",
  },
  {
    key: 7,
    name: "Gaming Headphones",
    image: image7,
    price: 49.32,
    description: "Eco-friendly",
  },
  {
    key: 8,
    name: "JBL Wireless Earbuds",
    image: image8,
    price: 32.40,
    description: "Connect with yourself",
  },
  {
    key: 9,
    name: "JBL Headphones",
    image: image9,
    price: 58.89,
    description: "Noise reduction, comfortable",
  },
];
